// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG8rE3_iGVTv32lvWPfbBvFH_qwftHVao',
    appId: '1:189963533612:web:c9e185af51b57538bf4089',
    messagingSenderId: '189963533612',
    projectId: 'fitness-e8d53',
    authDomain: 'fitness-e8d53.firebaseapp.com',
    storageBucket: 'fitness-e8d53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJVFLe818Dwn1iEC2g_v5P_ZaTplSLkPI',
    appId: '1:189963533612:android:288f915f80f08e1ebf4089',
    messagingSenderId: '189963533612',
    projectId: 'fitness-e8d53',
    storageBucket: 'fitness-e8d53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1GbBKatsXOZ12uOKG4RzA8bhKkm3x4Hg',
    appId: '1:189963533612:ios:864f57ff99c9ac7abf4089',
    messagingSenderId: '189963533612',
    projectId: 'fitness-e8d53',
    storageBucket: 'fitness-e8d53.appspot.com',
    iosClientId: '189963533612-7a23sjdn7pg9731t7o9s9oe1a1tafgo7.apps.googleusercontent.com',
    iosBundleId: 'com.nft.marketplace.nfts.mintit.nfts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1GbBKatsXOZ12uOKG4RzA8bhKkm3x4Hg',
    appId: '1:189963533612:ios:864f57ff99c9ac7abf4089',
    messagingSenderId: '189963533612',
    projectId: 'fitness-e8d53',
    storageBucket: 'fitness-e8d53.appspot.com',
    iosClientId: '189963533612-7a23sjdn7pg9731t7o9s9oe1a1tafgo7.apps.googleusercontent.com',
    iosBundleId: 'com.nft.marketplace.nfts.mintit.nfts',
  );
}
